### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [Toshiki003/Dressing-for-2-years-old-child#101]
※ 確認後クローズしてください
※ 遅くなってしまいすいません！

## サービスレビュー

* 2歳児の身支度にフォーカスしているところがニッチだけどペインが大きいところだと思うので、いいですね。
* 内容的にただの掲示板になってしまっているので、サービスの内容に沿った形でフックとなる機能を追加されるといいかなと思います。
* 投稿系だとCookpadを参考にしてみるといいかなと思います。例えば検索をタイトル、本文だけでなくカテゴリも追加し、タグやカテゴリ名はキーワード補完してあげたりすると就活する上でもフック機能になるかなと思います。

## 技術レビュー

https://github.com/Toshiki003/Dressing-for-2-years-old-child/blob/36752e4b0b64e1ecc756537a188150b0ad1241be/app/controllers/posts_controller.rb#L40

* これはマジックナンバーと同様で定数もしくはconfigに外出ししたほうがいいですね

https://github.com/Toshiki003/Dressing-for-2-years-old-child/blob/36752e4b0b64e1ecc756537a188150b0ad1241be/app/controllers/posts_controller.rb#L25

* Tagのクラスメソッドでもいいので、カンマ区切りの文字列からTagオブジェクトの配列に変換するメソッドなどを追加してsaveメソッドはそのままにした方が役割がすっきりするかなと思いました。

```
@post.tags = Tag.str2tags(params[: tag_names])
```

https://github.com/Toshiki003/Dressing-for-2-years-old-child/blob/36752e4b0b64e1ecc756537a188150b0ad1241be/app/controllers/posts_controller.rb#L59
https://github.com/Toshiki003/Dressing-for-2-years-old-child/blob/36752e4b0b64e1ecc756537a188150b0ad1241be/app/controllers/posts_controller.rb#L63

* 面倒でもbookmarksコントローラ、likesコントローラのindexに移動させたほうがRails的ですね。

https://github.com/Toshiki003/Dressing-for-2-years-old-child/blob/36752e4b0b64e1ecc756537a188150b0ad1241be/app/controllers/posts_controller.rb#L5

* ここもsearch_formに混ぜてしまっていいのかなと思いました

**Comment by Toshiki003** [comment]
お忙しい中でのレビューありがとうございます！
指摘していただいた箇所を調べ追加していきたいと思います。
また、機能面でフックとなる要素を入れるよう改善を続けていきたいと思います。
